#!/bin/tcsh

scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/FOF_Finite.p .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/FOF_Finite.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/FOF_Finite_Medium.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/FOF_Finite.s.p .

scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Finite.p .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Finite.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Finite_Medium.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Finite_Fine.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Finite_Compact.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Finite.s.p .
# scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Finite.sp.AGMV.p .

scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Infinite.p .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Integer.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Peano.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Integer.s.p .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/TFF_Peano.s.p .

scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Global.p .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Global.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Global_Medium.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Global_Fine.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Global_Compact.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Global.s.p .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Local.p .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Local.s .
scp tptp@quokka:/exp/home/tptp/public_html/TPTP/Proposals/InterpretationsModels/NTF_Finite-Finite-Local.s.p .
