#!/bin/tcsh

scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Finite.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Finite.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Finite.s.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Finite_Medium.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Saturation.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Saturation.s.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Formulae.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/FOF_Formulae.s.p .

scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite.s.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite_SeparateDomains.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite_SeparateDomains.s.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite_Medium.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite_Fine.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite_Compact.s .
# scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Finite.sp.AGMV.p .

scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Infinite.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Integer.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Peano.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Integer.s.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/TFF_Peano.s.p .

scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/THF_Finite.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/THF_Finite.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/THF_Finite_Medium.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/THF_Finite_Compact.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/THF_Finite.s.p .

scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Global.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Global.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Global_Medium.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Global_Fine.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Global_Compact.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Global.s.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Global.s.TXF.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Local.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Local.s .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Local.s.p .
scp tptp@quenda:/home/tptp/public_html/Proposals/InterpretationsModels/ModelExamples/NXF_Finite-Finite-Local.s.TXF.p .
